### ISSUE TITLE
你这个docker镜像多大啊

### ISSUE THREAD

**Issue by deeplearningers** [TableOCR-RPA/ppocr-server-docker#1]

**Comment by reonokiy** [comment]
1.58G，在dockerhub上 https://hub.docker.com/repository/docker/sperjar/ppocr/general ，这个是我们自己学习来用的，可能有一些问题，没怎么测试😂，

我记得PaddleOCR官方项目的issue里面有一个比官方小一点的镜像的提交，不过好像还没合并到主线上
